// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MetaVo.proto

package com.example.rsocket;

public final class MetaVo {
  private MetaVo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MetaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sdack.imio.Meta)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>int64 appId = 2;</code>
     * @return The appId.
     */
    long getAppId();

    /**
     * <code>double v = 3;</code>
     * @return The v.
     */
    double getV();

    /**
     * <pre>
     * 排序
     * </pre>
     *
     * <code>int32 sort = 4;</code>
     * @return The sort.
     */
    int getSort();

    /**
     * <code>string gmtCreate = 5;</code>
     * @return The gmtCreate.
     */
    String getGmtCreate();
    /**
     * <code>string gmtCreate = 5;</code>
     * @return The bytes for gmtCreate.
     */
    com.google.protobuf.ByteString
        getGmtCreateBytes();

    /**
     * <code>string gmtModified = 6;</code>
     * @return The gmtModified.
     */
    String getGmtModified();
    /**
     * <code>string gmtModified = 6;</code>
     * @return The bytes for gmtModified.
     */
    com.google.protobuf.ByteString
        getGmtModifiedBytes();

    /**
     * <code>repeated string ids = 7;</code>
     * @return A list containing the ids.
     */
    java.util.List<String>
        getIdsList();
    /**
     * <code>repeated string ids = 7;</code>
     * @return The count of ids.
     */
    int getIdsCount();
    /**
     * <code>repeated string ids = 7;</code>
     * @param index The index of the element to return.
     * @return The ids at the given index.
     */
    String getIds(int index);
    /**
     * <code>repeated string ids = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the ids at the given index.
     */
    com.google.protobuf.ByteString
        getIdsBytes(int index);

    /**
     * <code>repeated string appIds = 8;</code>
     * @return A list containing the appIds.
     */
    java.util.List<String>
        getAppIdsList();
    /**
     * <code>repeated string appIds = 8;</code>
     * @return The count of appIds.
     */
    int getAppIdsCount();
    /**
     * <code>repeated string appIds = 8;</code>
     * @param index The index of the element to return.
     * @return The appIds at the given index.
     */
    String getAppIds(int index);
    /**
     * <code>repeated string appIds = 8;</code>
     * @param index The index of the value to return.
     * @return The bytes of the appIds at the given index.
     */
    com.google.protobuf.ByteString
        getAppIdsBytes(int index);

    /**
     * <pre>
     * 所属用户
     * </pre>
     *
     * <code>string userId = 9;</code>
     * @return The userId.
     */
    String getUserId();
    /**
     * <pre>
     * 所属用户
     * </pre>
     *
     * <code>string userId = 9;</code>
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <pre>
     * 描述
     * </pre>
     *
     * <code>string describe = 10;</code>
     * @return The describe.
     */
    String getDescribe();
    /**
     * <pre>
     * 描述
     * </pre>
     *
     * <code>string describe = 10;</code>
     * @return The bytes for describe.
     */
    com.google.protobuf.ByteString
        getDescribeBytes();

    /**
     * <pre>
     * 备注
     * </pre>
     *
     * <code>string remark = 12;</code>
     * @return The remark.
     */
    String getRemark();
    /**
     * <pre>
     * 备注
     * </pre>
     *
     * <code>string remark = 12;</code>
     * @return The bytes for remark.
     */
    com.google.protobuf.ByteString
        getRemarkBytes();

    /**
     * <code>repeated int64 roomIds = 13;</code>
     * @return A list containing the roomIds.
     */
    java.util.List<Long> getRoomIdsList();
    /**
     * <code>repeated int64 roomIds = 13;</code>
     * @return The count of roomIds.
     */
    int getRoomIdsCount();
    /**
     * <code>repeated int64 roomIds = 13;</code>
     * @param index The index of the element to return.
     * @return The roomIds at the given index.
     */
    long getRoomIds(int index);

    /**
     * <code>repeated string keys = 14;</code>
     * @return A list containing the keys.
     */
    java.util.List<String>
        getKeysList();
    /**
     * <code>repeated string keys = 14;</code>
     * @return The count of keys.
     */
    int getKeysCount();
    /**
     * <code>repeated string keys = 14;</code>
     * @param index The index of the element to return.
     * @return The keys at the given index.
     */
    String getKeys(int index);
    /**
     * <code>repeated string keys = 14;</code>
     * @param index The index of the value to return.
     * @return The bytes of the keys at the given index.
     */
    com.google.protobuf.ByteString
        getKeysBytes(int index);

    /**
     * <code>repeated int64 userIds = 15;</code>
     * @return A list containing the userIds.
     */
    java.util.List<Long> getUserIdsList();
    /**
     * <code>repeated int64 userIds = 15;</code>
     * @return The count of userIds.
     */
    int getUserIdsCount();
    /**
     * <code>repeated int64 userIds = 15;</code>
     * @param index The index of the element to return.
     * @return The userIds at the given index.
     */
    long getUserIds(int index);
  }
  /**
   * Protobuf type {@code sdack.imio.Meta}
   */
  public static final class Meta extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sdack.imio.Meta)
      MetaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Meta.newBuilder() to construct.
    private Meta(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Meta() {
      id_ = "";
      gmtCreate_ = "";
      gmtModified_ = "";
      ids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      appIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      userId_ = "";
      describe_ = "";
      remark_ = "";
      roomIds_ = emptyLongList();
      keys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      userIds_ = emptyLongList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Meta();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Meta(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 16: {

              appId_ = input.readInt64();
              break;
            }
            case 25: {

              v_ = input.readDouble();
              break;
            }
            case 32: {

              sort_ = input.readInt32();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              gmtCreate_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              gmtModified_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                ids_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              ids_.add(s);
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                appIds_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              appIds_.add(s);
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 82: {
              String s = input.readStringRequireUtf8();

              describe_ = s;
              break;
            }
            case 98: {
              String s = input.readStringRequireUtf8();

              remark_ = s;
              break;
            }
            case 104: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                roomIds_ = newLongList();
                mutable_bitField0_ |= 0x00000004;
              }
              roomIds_.addLong(input.readInt64());
              break;
            }
            case 106: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) != 0) && input.getBytesUntilLimit() > 0) {
                roomIds_ = newLongList();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                roomIds_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 114: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                keys_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              keys_.add(s);
              break;
            }
            case 120: {
              if (!((mutable_bitField0_ & 0x00000010) != 0)) {
                userIds_ = newLongList();
                mutable_bitField0_ |= 0x00000010;
              }
              userIds_.addLong(input.readInt64());
              break;
            }
            case 122: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) != 0) && input.getBytesUntilLimit() > 0) {
                userIds_ = newLongList();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                userIds_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          ids_ = ids_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          appIds_ = appIds_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          roomIds_.makeImmutable(); // C
        }
        if (((mutable_bitField0_ & 0x00000008) != 0)) {
          keys_ = keys_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000010) != 0)) {
          userIds_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.rsocket.MetaVo.internal_static_sdack_imio_Meta_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.rsocket.MetaVo.internal_static_sdack_imio_Meta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.rsocket.MetaVo.Meta.class, com.example.rsocket.MetaVo.Meta.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @Override
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPID_FIELD_NUMBER = 2;
    private long appId_;
    /**
     * <code>int64 appId = 2;</code>
     * @return The appId.
     */
    @Override
    public long getAppId() {
      return appId_;
    }

    public static final int V_FIELD_NUMBER = 3;
    private double v_;
    /**
     * <code>double v = 3;</code>
     * @return The v.
     */
    @Override
    public double getV() {
      return v_;
    }

    public static final int SORT_FIELD_NUMBER = 4;
    private int sort_;
    /**
     * <pre>
     * 排序
     * </pre>
     *
     * <code>int32 sort = 4;</code>
     * @return The sort.
     */
    @Override
    public int getSort() {
      return sort_;
    }

    public static final int GMTCREATE_FIELD_NUMBER = 5;
    private volatile Object gmtCreate_;
    /**
     * <code>string gmtCreate = 5;</code>
     * @return The gmtCreate.
     */
    @Override
    public String getGmtCreate() {
      Object ref = gmtCreate_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        gmtCreate_ = s;
        return s;
      }
    }
    /**
     * <code>string gmtCreate = 5;</code>
     * @return The bytes for gmtCreate.
     */
    @Override
    public com.google.protobuf.ByteString
        getGmtCreateBytes() {
      Object ref = gmtCreate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        gmtCreate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GMTMODIFIED_FIELD_NUMBER = 6;
    private volatile Object gmtModified_;
    /**
     * <code>string gmtModified = 6;</code>
     * @return The gmtModified.
     */
    @Override
    public String getGmtModified() {
      Object ref = gmtModified_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        gmtModified_ = s;
        return s;
      }
    }
    /**
     * <code>string gmtModified = 6;</code>
     * @return The bytes for gmtModified.
     */
    @Override
    public com.google.protobuf.ByteString
        getGmtModifiedBytes() {
      Object ref = gmtModified_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        gmtModified_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IDS_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList ids_;
    /**
     * <code>repeated string ids = 7;</code>
     * @return A list containing the ids.
     */
    public com.google.protobuf.ProtocolStringList
        getIdsList() {
      return ids_;
    }
    /**
     * <code>repeated string ids = 7;</code>
     * @return The count of ids.
     */
    public int getIdsCount() {
      return ids_.size();
    }
    /**
     * <code>repeated string ids = 7;</code>
     * @param index The index of the element to return.
     * @return The ids at the given index.
     */
    public String getIds(int index) {
      return ids_.get(index);
    }
    /**
     * <code>repeated string ids = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the ids at the given index.
     */
    public com.google.protobuf.ByteString
        getIdsBytes(int index) {
      return ids_.getByteString(index);
    }

    public static final int APPIDS_FIELD_NUMBER = 8;
    private com.google.protobuf.LazyStringList appIds_;
    /**
     * <code>repeated string appIds = 8;</code>
     * @return A list containing the appIds.
     */
    public com.google.protobuf.ProtocolStringList
        getAppIdsList() {
      return appIds_;
    }
    /**
     * <code>repeated string appIds = 8;</code>
     * @return The count of appIds.
     */
    public int getAppIdsCount() {
      return appIds_.size();
    }
    /**
     * <code>repeated string appIds = 8;</code>
     * @param index The index of the element to return.
     * @return The appIds at the given index.
     */
    public String getAppIds(int index) {
      return appIds_.get(index);
    }
    /**
     * <code>repeated string appIds = 8;</code>
     * @param index The index of the value to return.
     * @return The bytes of the appIds at the given index.
     */
    public com.google.protobuf.ByteString
        getAppIdsBytes(int index) {
      return appIds_.getByteString(index);
    }

    public static final int USERID_FIELD_NUMBER = 9;
    private volatile Object userId_;
    /**
     * <pre>
     * 所属用户
     * </pre>
     *
     * <code>string userId = 9;</code>
     * @return The userId.
     */
    @Override
    public String getUserId() {
      Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 所属用户
     * </pre>
     *
     * <code>string userId = 9;</code>
     * @return The bytes for userId.
     */
    @Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIBE_FIELD_NUMBER = 10;
    private volatile Object describe_;
    /**
     * <pre>
     * 描述
     * </pre>
     *
     * <code>string describe = 10;</code>
     * @return The describe.
     */
    @Override
    public String getDescribe() {
      Object ref = describe_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        describe_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 描述
     * </pre>
     *
     * <code>string describe = 10;</code>
     * @return The bytes for describe.
     */
    @Override
    public com.google.protobuf.ByteString
        getDescribeBytes() {
      Object ref = describe_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        describe_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REMARK_FIELD_NUMBER = 12;
    private volatile Object remark_;
    /**
     * <pre>
     * 备注
     * </pre>
     *
     * <code>string remark = 12;</code>
     * @return The remark.
     */
    @Override
    public String getRemark() {
      Object ref = remark_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        remark_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 备注
     * </pre>
     *
     * <code>string remark = 12;</code>
     * @return The bytes for remark.
     */
    @Override
    public com.google.protobuf.ByteString
        getRemarkBytes() {
      Object ref = remark_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        remark_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROOMIDS_FIELD_NUMBER = 13;
    private com.google.protobuf.Internal.LongList roomIds_;
    /**
     * <code>repeated int64 roomIds = 13;</code>
     * @return A list containing the roomIds.
     */
    @Override
    public java.util.List<Long>
        getRoomIdsList() {
      return roomIds_;
    }
    /**
     * <code>repeated int64 roomIds = 13;</code>
     * @return The count of roomIds.
     */
    public int getRoomIdsCount() {
      return roomIds_.size();
    }
    /**
     * <code>repeated int64 roomIds = 13;</code>
     * @param index The index of the element to return.
     * @return The roomIds at the given index.
     */
    public long getRoomIds(int index) {
      return roomIds_.getLong(index);
    }
    private int roomIdsMemoizedSerializedSize = -1;

    public static final int KEYS_FIELD_NUMBER = 14;
    private com.google.protobuf.LazyStringList keys_;
    /**
     * <code>repeated string keys = 14;</code>
     * @return A list containing the keys.
     */
    public com.google.protobuf.ProtocolStringList
        getKeysList() {
      return keys_;
    }
    /**
     * <code>repeated string keys = 14;</code>
     * @return The count of keys.
     */
    public int getKeysCount() {
      return keys_.size();
    }
    /**
     * <code>repeated string keys = 14;</code>
     * @param index The index of the element to return.
     * @return The keys at the given index.
     */
    public String getKeys(int index) {
      return keys_.get(index);
    }
    /**
     * <code>repeated string keys = 14;</code>
     * @param index The index of the value to return.
     * @return The bytes of the keys at the given index.
     */
    public com.google.protobuf.ByteString
        getKeysBytes(int index) {
      return keys_.getByteString(index);
    }

    public static final int USERIDS_FIELD_NUMBER = 15;
    private com.google.protobuf.Internal.LongList userIds_;
    /**
     * <code>repeated int64 userIds = 15;</code>
     * @return A list containing the userIds.
     */
    @Override
    public java.util.List<Long>
        getUserIdsList() {
      return userIds_;
    }
    /**
     * <code>repeated int64 userIds = 15;</code>
     * @return The count of userIds.
     */
    public int getUserIdsCount() {
      return userIds_.size();
    }
    /**
     * <code>repeated int64 userIds = 15;</code>
     * @param index The index of the element to return.
     * @return The userIds at the given index.
     */
    public long getUserIds(int index) {
      return userIds_.getLong(index);
    }
    private int userIdsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (appId_ != 0L) {
        output.writeInt64(2, appId_);
      }
      if (v_ != 0D) {
        output.writeDouble(3, v_);
      }
      if (sort_ != 0) {
        output.writeInt32(4, sort_);
      }
      if (!getGmtCreateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, gmtCreate_);
      }
      if (!getGmtModifiedBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, gmtModified_);
      }
      for (int i = 0; i < ids_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, ids_.getRaw(i));
      }
      for (int i = 0; i < appIds_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, appIds_.getRaw(i));
      }
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, userId_);
      }
      if (!getDescribeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, describe_);
      }
      if (!getRemarkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, remark_);
      }
      if (getRoomIdsList().size() > 0) {
        output.writeUInt32NoTag(106);
        output.writeUInt32NoTag(roomIdsMemoizedSerializedSize);
      }
      for (int i = 0; i < roomIds_.size(); i++) {
        output.writeInt64NoTag(roomIds_.getLong(i));
      }
      for (int i = 0; i < keys_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, keys_.getRaw(i));
      }
      if (getUserIdsList().size() > 0) {
        output.writeUInt32NoTag(122);
        output.writeUInt32NoTag(userIdsMemoizedSerializedSize);
      }
      for (int i = 0; i < userIds_.size(); i++) {
        output.writeInt64NoTag(userIds_.getLong(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (appId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, appId_);
      }
      if (v_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, v_);
      }
      if (sort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, sort_);
      }
      if (!getGmtCreateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, gmtCreate_);
      }
      if (!getGmtModifiedBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, gmtModified_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < ids_.size(); i++) {
          dataSize += computeStringSizeNoTag(ids_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getIdsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < appIds_.size(); i++) {
          dataSize += computeStringSizeNoTag(appIds_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAppIdsList().size();
      }
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, userId_);
      }
      if (!getDescribeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, describe_);
      }
      if (!getRemarkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, remark_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < roomIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(roomIds_.getLong(i));
        }
        size += dataSize;
        if (!getRoomIdsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        roomIdsMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < keys_.size(); i++) {
          dataSize += computeStringSizeNoTag(keys_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getKeysList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < userIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(userIds_.getLong(i));
        }
        size += dataSize;
        if (!getUserIdsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        userIdsMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.rsocket.MetaVo.Meta)) {
        return super.equals(obj);
      }
      com.example.rsocket.MetaVo.Meta other = (com.example.rsocket.MetaVo.Meta) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (getAppId()
          != other.getAppId()) return false;
      if (Double.doubleToLongBits(getV())
          != Double.doubleToLongBits(
              other.getV())) return false;
      if (getSort()
          != other.getSort()) return false;
      if (!getGmtCreate()
          .equals(other.getGmtCreate())) return false;
      if (!getGmtModified()
          .equals(other.getGmtModified())) return false;
      if (!getIdsList()
          .equals(other.getIdsList())) return false;
      if (!getAppIdsList()
          .equals(other.getAppIdsList())) return false;
      if (!getUserId()
          .equals(other.getUserId())) return false;
      if (!getDescribe()
          .equals(other.getDescribe())) return false;
      if (!getRemark()
          .equals(other.getRemark())) return false;
      if (!getRoomIdsList()
          .equals(other.getRoomIdsList())) return false;
      if (!getKeysList()
          .equals(other.getKeysList())) return false;
      if (!getUserIdsList()
          .equals(other.getUserIdsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + APPID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAppId());
      hash = (37 * hash) + V_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getV()));
      hash = (37 * hash) + SORT_FIELD_NUMBER;
      hash = (53 * hash) + getSort();
      hash = (37 * hash) + GMTCREATE_FIELD_NUMBER;
      hash = (53 * hash) + getGmtCreate().hashCode();
      hash = (37 * hash) + GMTMODIFIED_FIELD_NUMBER;
      hash = (53 * hash) + getGmtModified().hashCode();
      if (getIdsCount() > 0) {
        hash = (37 * hash) + IDS_FIELD_NUMBER;
        hash = (53 * hash) + getIdsList().hashCode();
      }
      if (getAppIdsCount() > 0) {
        hash = (37 * hash) + APPIDS_FIELD_NUMBER;
        hash = (53 * hash) + getAppIdsList().hashCode();
      }
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + DESCRIBE_FIELD_NUMBER;
      hash = (53 * hash) + getDescribe().hashCode();
      hash = (37 * hash) + REMARK_FIELD_NUMBER;
      hash = (53 * hash) + getRemark().hashCode();
      if (getRoomIdsCount() > 0) {
        hash = (37 * hash) + ROOMIDS_FIELD_NUMBER;
        hash = (53 * hash) + getRoomIdsList().hashCode();
      }
      if (getKeysCount() > 0) {
        hash = (37 * hash) + KEYS_FIELD_NUMBER;
        hash = (53 * hash) + getKeysList().hashCode();
      }
      if (getUserIdsCount() > 0) {
        hash = (37 * hash) + USERIDS_FIELD_NUMBER;
        hash = (53 * hash) + getUserIdsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.rsocket.MetaVo.Meta parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.rsocket.MetaVo.Meta parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.rsocket.MetaVo.Meta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.rsocket.MetaVo.Meta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.rsocket.MetaVo.Meta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.rsocket.MetaVo.Meta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.rsocket.MetaVo.Meta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.rsocket.MetaVo.Meta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.rsocket.MetaVo.Meta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.rsocket.MetaVo.Meta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.rsocket.MetaVo.Meta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.rsocket.MetaVo.Meta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.rsocket.MetaVo.Meta prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sdack.imio.Meta}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sdack.imio.Meta)
        com.example.rsocket.MetaVo.MetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.rsocket.MetaVo.internal_static_sdack_imio_Meta_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.rsocket.MetaVo.internal_static_sdack_imio_Meta_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.rsocket.MetaVo.Meta.class, com.example.rsocket.MetaVo.Meta.Builder.class);
      }

      // Construct using com.example.rsocket.MetaVo.Meta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = "";

        appId_ = 0L;

        v_ = 0D;

        sort_ = 0;

        gmtCreate_ = "";

        gmtModified_ = "";

        ids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        appIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = "";

        describe_ = "";

        remark_ = "";

        roomIds_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000004);
        keys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        userIds_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.rsocket.MetaVo.internal_static_sdack_imio_Meta_descriptor;
      }

      @Override
      public com.example.rsocket.MetaVo.Meta getDefaultInstanceForType() {
        return com.example.rsocket.MetaVo.Meta.getDefaultInstance();
      }

      @Override
      public com.example.rsocket.MetaVo.Meta build() {
        com.example.rsocket.MetaVo.Meta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.example.rsocket.MetaVo.Meta buildPartial() {
        com.example.rsocket.MetaVo.Meta result = new com.example.rsocket.MetaVo.Meta(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.appId_ = appId_;
        result.v_ = v_;
        result.sort_ = sort_;
        result.gmtCreate_ = gmtCreate_;
        result.gmtModified_ = gmtModified_;
        if (((bitField0_ & 0x00000001) != 0)) {
          ids_ = ids_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ids_ = ids_;
        if (((bitField0_ & 0x00000002) != 0)) {
          appIds_ = appIds_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.appIds_ = appIds_;
        result.userId_ = userId_;
        result.describe_ = describe_;
        result.remark_ = remark_;
        if (((bitField0_ & 0x00000004) != 0)) {
          roomIds_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.roomIds_ = roomIds_;
        if (((bitField0_ & 0x00000008) != 0)) {
          keys_ = keys_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.keys_ = keys_;
        if (((bitField0_ & 0x00000010) != 0)) {
          userIds_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.userIds_ = userIds_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.rsocket.MetaVo.Meta) {
          return mergeFrom((com.example.rsocket.MetaVo.Meta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.rsocket.MetaVo.Meta other) {
        if (other == com.example.rsocket.MetaVo.Meta.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getAppId() != 0L) {
          setAppId(other.getAppId());
        }
        if (other.getV() != 0D) {
          setV(other.getV());
        }
        if (other.getSort() != 0) {
          setSort(other.getSort());
        }
        if (!other.getGmtCreate().isEmpty()) {
          gmtCreate_ = other.gmtCreate_;
          onChanged();
        }
        if (!other.getGmtModified().isEmpty()) {
          gmtModified_ = other.gmtModified_;
          onChanged();
        }
        if (!other.ids_.isEmpty()) {
          if (ids_.isEmpty()) {
            ids_ = other.ids_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIdsIsMutable();
            ids_.addAll(other.ids_);
          }
          onChanged();
        }
        if (!other.appIds_.isEmpty()) {
          if (appIds_.isEmpty()) {
            appIds_ = other.appIds_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureAppIdsIsMutable();
            appIds_.addAll(other.appIds_);
          }
          onChanged();
        }
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getDescribe().isEmpty()) {
          describe_ = other.describe_;
          onChanged();
        }
        if (!other.getRemark().isEmpty()) {
          remark_ = other.remark_;
          onChanged();
        }
        if (!other.roomIds_.isEmpty()) {
          if (roomIds_.isEmpty()) {
            roomIds_ = other.roomIds_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureRoomIdsIsMutable();
            roomIds_.addAll(other.roomIds_);
          }
          onChanged();
        }
        if (!other.keys_.isEmpty()) {
          if (keys_.isEmpty()) {
            keys_ = other.keys_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureKeysIsMutable();
            keys_.addAll(other.keys_);
          }
          onChanged();
        }
        if (!other.userIds_.isEmpty()) {
          if (userIds_.isEmpty()) {
            userIds_ = other.userIds_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureUserIdsIsMutable();
            userIds_.addAll(other.userIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.rsocket.MetaVo.Meta parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.rsocket.MetaVo.Meta) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private long appId_ ;
      /**
       * <code>int64 appId = 2;</code>
       * @return The appId.
       */
      @Override
      public long getAppId() {
        return appId_;
      }
      /**
       * <code>int64 appId = 2;</code>
       * @param value The appId to set.
       * @return This builder for chaining.
       */
      public Builder setAppId(long value) {
        
        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 appId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAppId() {
        
        appId_ = 0L;
        onChanged();
        return this;
      }

      private double v_ ;
      /**
       * <code>double v = 3;</code>
       * @return The v.
       */
      @Override
      public double getV() {
        return v_;
      }
      /**
       * <code>double v = 3;</code>
       * @param value The v to set.
       * @return This builder for chaining.
       */
      public Builder setV(double value) {
        
        v_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double v = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearV() {
        
        v_ = 0D;
        onChanged();
        return this;
      }

      private int sort_ ;
      /**
       * <pre>
       * 排序
       * </pre>
       *
       * <code>int32 sort = 4;</code>
       * @return The sort.
       */
      @Override
      public int getSort() {
        return sort_;
      }
      /**
       * <pre>
       * 排序
       * </pre>
       *
       * <code>int32 sort = 4;</code>
       * @param value The sort to set.
       * @return This builder for chaining.
       */
      public Builder setSort(int value) {
        
        sort_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 排序
       * </pre>
       *
       * <code>int32 sort = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSort() {
        
        sort_ = 0;
        onChanged();
        return this;
      }

      private Object gmtCreate_ = "";
      /**
       * <code>string gmtCreate = 5;</code>
       * @return The gmtCreate.
       */
      public String getGmtCreate() {
        Object ref = gmtCreate_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          gmtCreate_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string gmtCreate = 5;</code>
       * @return The bytes for gmtCreate.
       */
      public com.google.protobuf.ByteString
          getGmtCreateBytes() {
        Object ref = gmtCreate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          gmtCreate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string gmtCreate = 5;</code>
       * @param value The gmtCreate to set.
       * @return This builder for chaining.
       */
      public Builder setGmtCreate(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gmtCreate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string gmtCreate = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearGmtCreate() {
        
        gmtCreate_ = getDefaultInstance().getGmtCreate();
        onChanged();
        return this;
      }
      /**
       * <code>string gmtCreate = 5;</code>
       * @param value The bytes for gmtCreate to set.
       * @return This builder for chaining.
       */
      public Builder setGmtCreateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gmtCreate_ = value;
        onChanged();
        return this;
      }

      private Object gmtModified_ = "";
      /**
       * <code>string gmtModified = 6;</code>
       * @return The gmtModified.
       */
      public String getGmtModified() {
        Object ref = gmtModified_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          gmtModified_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string gmtModified = 6;</code>
       * @return The bytes for gmtModified.
       */
      public com.google.protobuf.ByteString
          getGmtModifiedBytes() {
        Object ref = gmtModified_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          gmtModified_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string gmtModified = 6;</code>
       * @param value The gmtModified to set.
       * @return This builder for chaining.
       */
      public Builder setGmtModified(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gmtModified_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string gmtModified = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearGmtModified() {
        
        gmtModified_ = getDefaultInstance().getGmtModified();
        onChanged();
        return this;
      }
      /**
       * <code>string gmtModified = 6;</code>
       * @param value The bytes for gmtModified to set.
       * @return This builder for chaining.
       */
      public Builder setGmtModifiedBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gmtModified_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList ids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureIdsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          ids_ = new com.google.protobuf.LazyStringArrayList(ids_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string ids = 7;</code>
       * @return A list containing the ids.
       */
      public com.google.protobuf.ProtocolStringList
          getIdsList() {
        return ids_.getUnmodifiableView();
      }
      /**
       * <code>repeated string ids = 7;</code>
       * @return The count of ids.
       */
      public int getIdsCount() {
        return ids_.size();
      }
      /**
       * <code>repeated string ids = 7;</code>
       * @param index The index of the element to return.
       * @return The ids at the given index.
       */
      public String getIds(int index) {
        return ids_.get(index);
      }
      /**
       * <code>repeated string ids = 7;</code>
       * @param index The index of the value to return.
       * @return The bytes of the ids at the given index.
       */
      public com.google.protobuf.ByteString
          getIdsBytes(int index) {
        return ids_.getByteString(index);
      }
      /**
       * <code>repeated string ids = 7;</code>
       * @param index The index to set the value at.
       * @param value The ids to set.
       * @return This builder for chaining.
       */
      public Builder setIds(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIdsIsMutable();
        ids_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ids = 7;</code>
       * @param value The ids to add.
       * @return This builder for chaining.
       */
      public Builder addIds(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIdsIsMutable();
        ids_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ids = 7;</code>
       * @param values The ids to add.
       * @return This builder for chaining.
       */
      public Builder addAllIds(
          Iterable<String> values) {
        ensureIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ids_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ids = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearIds() {
        ids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ids = 7;</code>
       * @param value The bytes of the ids to add.
       * @return This builder for chaining.
       */
      public Builder addIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureIdsIsMutable();
        ids_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList appIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAppIdsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          appIds_ = new com.google.protobuf.LazyStringArrayList(appIds_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string appIds = 8;</code>
       * @return A list containing the appIds.
       */
      public com.google.protobuf.ProtocolStringList
          getAppIdsList() {
        return appIds_.getUnmodifiableView();
      }
      /**
       * <code>repeated string appIds = 8;</code>
       * @return The count of appIds.
       */
      public int getAppIdsCount() {
        return appIds_.size();
      }
      /**
       * <code>repeated string appIds = 8;</code>
       * @param index The index of the element to return.
       * @return The appIds at the given index.
       */
      public String getAppIds(int index) {
        return appIds_.get(index);
      }
      /**
       * <code>repeated string appIds = 8;</code>
       * @param index The index of the value to return.
       * @return The bytes of the appIds at the given index.
       */
      public com.google.protobuf.ByteString
          getAppIdsBytes(int index) {
        return appIds_.getByteString(index);
      }
      /**
       * <code>repeated string appIds = 8;</code>
       * @param index The index to set the value at.
       * @param value The appIds to set.
       * @return This builder for chaining.
       */
      public Builder setAppIds(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAppIdsIsMutable();
        appIds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string appIds = 8;</code>
       * @param value The appIds to add.
       * @return This builder for chaining.
       */
      public Builder addAppIds(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAppIdsIsMutable();
        appIds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string appIds = 8;</code>
       * @param values The appIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllAppIds(
          Iterable<String> values) {
        ensureAppIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, appIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string appIds = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearAppIds() {
        appIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string appIds = 8;</code>
       * @param value The bytes of the appIds to add.
       * @return This builder for chaining.
       */
      public Builder addAppIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureAppIdsIsMutable();
        appIds_.add(value);
        onChanged();
        return this;
      }

      private Object userId_ = "";
      /**
       * <pre>
       * 所属用户
       * </pre>
       *
       * <code>string userId = 9;</code>
       * @return The userId.
       */
      public String getUserId() {
        Object ref = userId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 所属用户
       * </pre>
       *
       * <code>string userId = 9;</code>
       * @return The bytes for userId.
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 所属用户
       * </pre>
       *
       * <code>string userId = 9;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 所属用户
       * </pre>
       *
       * <code>string userId = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 所属用户
       * </pre>
       *
       * <code>string userId = 9;</code>
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private Object describe_ = "";
      /**
       * <pre>
       * 描述
       * </pre>
       *
       * <code>string describe = 10;</code>
       * @return The describe.
       */
      public String getDescribe() {
        Object ref = describe_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          describe_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 描述
       * </pre>
       *
       * <code>string describe = 10;</code>
       * @return The bytes for describe.
       */
      public com.google.protobuf.ByteString
          getDescribeBytes() {
        Object ref = describe_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          describe_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 描述
       * </pre>
       *
       * <code>string describe = 10;</code>
       * @param value The describe to set.
       * @return This builder for chaining.
       */
      public Builder setDescribe(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        describe_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 描述
       * </pre>
       *
       * <code>string describe = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescribe() {
        
        describe_ = getDefaultInstance().getDescribe();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 描述
       * </pre>
       *
       * <code>string describe = 10;</code>
       * @param value The bytes for describe to set.
       * @return This builder for chaining.
       */
      public Builder setDescribeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        describe_ = value;
        onChanged();
        return this;
      }

      private Object remark_ = "";
      /**
       * <pre>
       * 备注
       * </pre>
       *
       * <code>string remark = 12;</code>
       * @return The remark.
       */
      public String getRemark() {
        Object ref = remark_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          remark_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 备注
       * </pre>
       *
       * <code>string remark = 12;</code>
       * @return The bytes for remark.
       */
      public com.google.protobuf.ByteString
          getRemarkBytes() {
        Object ref = remark_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          remark_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 备注
       * </pre>
       *
       * <code>string remark = 12;</code>
       * @param value The remark to set.
       * @return This builder for chaining.
       */
      public Builder setRemark(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        remark_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 备注
       * </pre>
       *
       * <code>string remark = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearRemark() {
        
        remark_ = getDefaultInstance().getRemark();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 备注
       * </pre>
       *
       * <code>string remark = 12;</code>
       * @param value The bytes for remark to set.
       * @return This builder for chaining.
       */
      public Builder setRemarkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        remark_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.LongList roomIds_ = emptyLongList();
      private void ensureRoomIdsIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          roomIds_ = mutableCopy(roomIds_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int64 roomIds = 13;</code>
       * @return A list containing the roomIds.
       */
      public java.util.List<Long>
          getRoomIdsList() {
        return ((bitField0_ & 0x00000004) != 0) ?
                 java.util.Collections.unmodifiableList(roomIds_) : roomIds_;
      }
      /**
       * <code>repeated int64 roomIds = 13;</code>
       * @return The count of roomIds.
       */
      public int getRoomIdsCount() {
        return roomIds_.size();
      }
      /**
       * <code>repeated int64 roomIds = 13;</code>
       * @param index The index of the element to return.
       * @return The roomIds at the given index.
       */
      public long getRoomIds(int index) {
        return roomIds_.getLong(index);
      }
      /**
       * <code>repeated int64 roomIds = 13;</code>
       * @param index The index to set the value at.
       * @param value The roomIds to set.
       * @return This builder for chaining.
       */
      public Builder setRoomIds(
          int index, long value) {
        ensureRoomIdsIsMutable();
        roomIds_.setLong(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 roomIds = 13;</code>
       * @param value The roomIds to add.
       * @return This builder for chaining.
       */
      public Builder addRoomIds(long value) {
        ensureRoomIdsIsMutable();
        roomIds_.addLong(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 roomIds = 13;</code>
       * @param values The roomIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllRoomIds(
          Iterable<? extends Long> values) {
        ensureRoomIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, roomIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 roomIds = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoomIds() {
        roomIds_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList keys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureKeysIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          keys_ = new com.google.protobuf.LazyStringArrayList(keys_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string keys = 14;</code>
       * @return A list containing the keys.
       */
      public com.google.protobuf.ProtocolStringList
          getKeysList() {
        return keys_.getUnmodifiableView();
      }
      /**
       * <code>repeated string keys = 14;</code>
       * @return The count of keys.
       */
      public int getKeysCount() {
        return keys_.size();
      }
      /**
       * <code>repeated string keys = 14;</code>
       * @param index The index of the element to return.
       * @return The keys at the given index.
       */
      public String getKeys(int index) {
        return keys_.get(index);
      }
      /**
       * <code>repeated string keys = 14;</code>
       * @param index The index of the value to return.
       * @return The bytes of the keys at the given index.
       */
      public com.google.protobuf.ByteString
          getKeysBytes(int index) {
        return keys_.getByteString(index);
      }
      /**
       * <code>repeated string keys = 14;</code>
       * @param index The index to set the value at.
       * @param value The keys to set.
       * @return This builder for chaining.
       */
      public Builder setKeys(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureKeysIsMutable();
        keys_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string keys = 14;</code>
       * @param value The keys to add.
       * @return This builder for chaining.
       */
      public Builder addKeys(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureKeysIsMutable();
        keys_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string keys = 14;</code>
       * @param values The keys to add.
       * @return This builder for chaining.
       */
      public Builder addAllKeys(
          Iterable<String> values) {
        ensureKeysIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, keys_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string keys = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearKeys() {
        keys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string keys = 14;</code>
       * @param value The bytes of the keys to add.
       * @return This builder for chaining.
       */
      public Builder addKeysBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureKeysIsMutable();
        keys_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.LongList userIds_ = emptyLongList();
      private void ensureUserIdsIsMutable() {
        if (!((bitField0_ & 0x00000010) != 0)) {
          userIds_ = mutableCopy(userIds_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated int64 userIds = 15;</code>
       * @return A list containing the userIds.
       */
      public java.util.List<Long>
          getUserIdsList() {
        return ((bitField0_ & 0x00000010) != 0) ?
                 java.util.Collections.unmodifiableList(userIds_) : userIds_;
      }
      /**
       * <code>repeated int64 userIds = 15;</code>
       * @return The count of userIds.
       */
      public int getUserIdsCount() {
        return userIds_.size();
      }
      /**
       * <code>repeated int64 userIds = 15;</code>
       * @param index The index of the element to return.
       * @return The userIds at the given index.
       */
      public long getUserIds(int index) {
        return userIds_.getLong(index);
      }
      /**
       * <code>repeated int64 userIds = 15;</code>
       * @param index The index to set the value at.
       * @param value The userIds to set.
       * @return This builder for chaining.
       */
      public Builder setUserIds(
          int index, long value) {
        ensureUserIdsIsMutable();
        userIds_.setLong(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 userIds = 15;</code>
       * @param value The userIds to add.
       * @return This builder for chaining.
       */
      public Builder addUserIds(long value) {
        ensureUserIdsIsMutable();
        userIds_.addLong(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 userIds = 15;</code>
       * @param values The userIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllUserIds(
          Iterable<? extends Long> values) {
        ensureUserIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, userIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 userIds = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserIds() {
        userIds_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sdack.imio.Meta)
    }

    // @@protoc_insertion_point(class_scope:sdack.imio.Meta)
    private static final com.example.rsocket.MetaVo.Meta DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.rsocket.MetaVo.Meta();
    }

    public static com.example.rsocket.MetaVo.Meta getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Meta>
        PARSER = new com.google.protobuf.AbstractParser<Meta>() {
      @Override
      public Meta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Meta(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Meta> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Meta> getParserForType() {
      return PARSER;
    }

    @Override
    public com.example.rsocket.MetaVo.Meta getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdack_imio_Meta_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sdack_imio_Meta_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014MetaVo.proto\022\nsdack.imio\"\341\001\n\004Meta\022\n\n\002i" +
      "d\030\001 \001(\t\022\r\n\005appId\030\002 \001(\003\022\t\n\001v\030\003 \001(\001\022\014\n\004sor" +
      "t\030\004 \001(\005\022\021\n\tgmtCreate\030\005 \001(\t\022\023\n\013gmtModifie" +
      "d\030\006 \001(\t\022\013\n\003ids\030\007 \003(\t\022\016\n\006appIds\030\010 \003(\t\022\016\n\006" +
      "userId\030\t \001(\t\022\020\n\010describe\030\n \001(\t\022\016\n\006remark" +
      "\030\014 \001(\t\022\017\n\007roomIds\030\r \003(\003\022\014\n\004keys\030\016 \003(\t\022\017\n" +
      "\007userIds\030\017 \003(\003B&\n\034cn.sdack.imio.common.m" +
      "essageB\006MetaVob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_sdack_imio_Meta_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sdack_imio_Meta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sdack_imio_Meta_descriptor,
        new String[] { "Id", "AppId", "V", "Sort", "GmtCreate", "GmtModified", "Ids", "AppIds", "UserId", "Describe", "Remark", "RoomIds", "Keys", "UserIds", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
